/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.src;

import Backend.HiProject;
import Backend.Project;
import Backend.ProjectsList;
import Backend.Serialization;

import javax.swing.*;
import java.time.LocalDate;

/**
 *
 * @author joaod
 */
public class EditProject extends javax.swing.JDialog {
    private Project selectedProject;
    private Serialization serialization = new Serialization(String.format("%s\\HiProject.data", System.getProperty("user.dir")));
    private HiProject hiProject = serialization.load();

    /**
     * Creates new form EditProject
     */
    public EditProject(java.awt.Frame parent, boolean modal, Project project) {
        super(parent, modal);
        selectedProject = hiProject.getProjects().getProject(project.getProjectID());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editYourSelectedProjectLabel = new javax.swing.JLabel();
        projectEndDateLabel = new javax.swing.JLabel();
        projectTitleLabel = new javax.swing.JLabel();
        projectDescriptionLabel = new javax.swing.JLabel();
        projectTitleValue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectDescriptionValue = new javax.swing.JTextArea();
        saveChangesButton = new javax.swing.JButton();
        exitDontSaveButton = new javax.swing.JButton();
        projectEndDateValue = new com.github.lgooddatepicker.components.DatePicker();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Project");
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(540, 510));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setLayout(null);

        editYourSelectedProjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editYourSelectedProjectLabel.setText("Edit Your Selected Project");
        editYourSelectedProjectLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(editYourSelectedProjectLabel);
        editYourSelectedProjectLabel.setBounds(0, 24, 540, 52);

        projectEndDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        projectEndDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        projectEndDateLabel.setText("Project End Date:");
        jPanel1.add(projectEndDateLabel);
        projectEndDateLabel.setBounds(10, 163, 150, 35);

        projectTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        projectTitleLabel.setText("Project Title:");
        projectTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(projectTitleLabel);
        projectTitleLabel.setBounds(10, 108, 150, 35);

        projectDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        projectDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        projectDescriptionLabel.setText("Project Description:");
        jPanel1.add(projectDescriptionLabel);
        projectDescriptionLabel.setBounds(10, 216, 150, 35);

        projectTitleValue.setText(selectedProject.getTitle());
        projectTitleValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectTitleValueActionPerformed(evt);
            }
        });
        jPanel1.add(projectTitleValue);
        projectTitleValue.setBounds(196, 110, 280, 35);

        projectDescriptionValue.setColumns(20);
        projectDescriptionValue.setRows(5);
        projectDescriptionValue.setText(selectedProject.getDescription());
        jScrollPane1.setViewportView(projectDescriptionValue);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(196, 216, 280, 180);

        saveChangesButton.setText("Save Changes");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveChangesButton);
        saveChangesButton.setBounds(64, 449, 116, 23);

        exitDontSaveButton.setText("Exit and Don't Save");
        jPanel1.add(exitDontSaveButton);
        exitDontSaveButton.setBounds(297, 449, 139, 23);

        projectEndDateValue.setDate(LocalDate.now().plusDays(1)
        );
        projectEndDateValue.setMinimumSize(new java.awt.Dimension(145, 25));
        jPanel1.add(projectEndDateValue);
        projectEndDateValue.setBounds(200, 170, 280, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(String.format("%s\\Images\\DefaultBackground.png", System.getProperty("user.dir"))));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(553, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void projectTitleValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectTitleValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectTitleValueActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        if (hiProject.getConnectedUser().getProjects().exists(projectTitleValue.getText())) {
            JOptionPane.showMessageDialog(null, "A project with this title already exists, please try again with a different one.", "Project Already Exists", JOptionPane.WARNING_MESSAGE);
            projectTitleValue.requestFocus();
        } else if (projectEndDateValue.getDate().isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(null, "Please insert a valid project end date.");
            projectTitleValue.requestFocus();
        } else if (projectDescriptionValue.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Please insert a project description.", "Project Description", JOptionPane.WARNING_MESSAGE);
            projectDescriptionValue.requestFocus();
        } else {
            ProjectsList updatedProjects = hiProject.getProjects();
            updatedProjects.getProject(selectedProject.getProjectID()).setTitle(projectTitleValue.getText());
            updatedProjects.getProject(selectedProject.getProjectID()).setEndDate(projectEndDateValue.getDate());
            updatedProjects.getProject(selectedProject.getProjectID()).setDescription(projectDescriptionValue.getText());
            hiProject.setProjects(updatedProjects);
            updatedProjects = hiProject.getConnectedUser().getProjects();
            updatedProjects.getProject(selectedProject.getProjectID()).setTitle(projectTitleValue.getText());
            updatedProjects.getProject(selectedProject.getProjectID()).setEndDate(projectEndDateValue.getDate());
            updatedProjects.getProject(selectedProject.getProjectID()).setDescription(projectDescriptionValue.getText());
            hiProject.getConnectedUser().setProjects(updatedProjects);
            serialization.save(hiProject);
            dispose();
        }
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editYourSelectedProjectLabel;
    private javax.swing.JButton exitDontSaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel projectDescriptionLabel;
    private javax.swing.JTextArea projectDescriptionValue;
    private javax.swing.JLabel projectEndDateLabel;
    private com.github.lgooddatepicker.components.DatePicker projectEndDateValue;
    private javax.swing.JLabel projectTitleLabel;
    private javax.swing.JTextField projectTitleValue;
    private javax.swing.JButton saveChangesButton;
    // End of variables declaration//GEN-END:variables
}
