/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.src;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.time.LocalDate;
import java.util.*;

import Backend.*;
import Exceptions.UserDoesntExistException;

import java.lang.reflect.Array;

import javax.swing.*;

/**
 * @author joaod
 */
public class Homepage extends javax.swing.JFrame {
    private static User connectedUser;
    private Map<Integer, Project> pl;
    private static ArrayList<String> titles = new ArrayList<>();
    private ArrayList<String> projectsmta(ArrayList<String> ptitles) {
        ptitles.clear();
        ptitles.add("< Please Select a Project >");
        for (Map.Entry<Integer, Project> e : pl.entrySet()) {
            ptitles.add(e.getValue().getTitle());
        }
        return ptitles;
    }

    /**
     * Creates new form Homepage
     */
    public Homepage(User connectedUser) {
        Homepage.connectedUser = connectedUser;
        pl = connectedUser.getProjects().getProjects();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        projectListComboBox = new javax.swing.JComboBox<>();
        editProfileButton = new javax.swing.JButton();
        addProjectButton = new javax.swing.JLabel();
        removeProjectButton = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        selectedProjectPanel = new javax.swing.JPanel();
        selectedProjectOwnerValue1 = new javax.swing.JLabel();
        selectedProjectStartDateValue1 = new javax.swing.JLabel();
        selectedProjectStartDateLabel1 = new javax.swing.JLabel();
        selectedProjectProjectStateLabel1 = new javax.swing.JLabel();
        selectedProjectTasksNumberLabel1 = new javax.swing.JLabel();
        selectedProjectEndDateLabel1 = new javax.swing.JLabel();
        selectedProjectEndDateValue1 = new javax.swing.JLabel();
        selectedProjectPeopleInvolvedLabel1 = new javax.swing.JLabel();
        selectedProjectOwnerLabel1 = new javax.swing.JLabel();
        selectedProjectProjectStateValue1 = new javax.swing.JLabel();
        selectedProjectNameLabel1 = new javax.swing.JLabel();
        selectedProjectTasksNumberValue1 = new javax.swing.JLabel();
        selectedProjectPeopleInvolvedValue1 = new javax.swing.JLabel();
        selectedProjectBackground = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        lateProjectsLabel = new javax.swing.JLabel();
        ongoingProjectsLabel = new javax.swing.JLabel();
        completedProjectsLabel = new javax.swing.JLabel();
        completedProjectsValueLabel = new javax.swing.JLabel();
        ongoingProjectsValueLabel = new javax.swing.JLabel();
        lateProjectsValueLabel = new javax.swing.JLabel();
        inNeedOfAttentionLabel = new javax.swing.JLabel();
        inoaProject2ValueLabel = new javax.swing.JLabel();
        inoaProject3ValueLabel = new javax.swing.JLabel();
        inoaProject1ValueLabel = new javax.swing.JLabel();
        biggestProjectLabel = new javax.swing.JLabel();
        bpPeopleInvolvedLabel = new javax.swing.JLabel();
        bpPeopleInvolvedValueLabel = new javax.swing.JLabel();
        bpCompletedTasksLabel = new javax.swing.JLabel();
        bpNameValueLabel = new javax.swing.JLabel();
        bpCompletedTasksValueLabel = new javax.swing.JLabel();
        dashboardBackground = new javax.swing.JLabel();
        homepageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Homepage");
        getContentPane().setLayout(null);

        mainMenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Welcome to HiProject, " + connectedUser.getName()));
        mainMenuPanel.setOpaque(false);
        mainMenuPanel.setLayout(null);

        projectListComboBox.setModel(new javax.swing.DefaultComboBoxModel(projectsmta(titles).toArray()));
        projectListComboBox.addItemListener (new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                /*String ptitle = projectListComboBox.getItemAt(projectListComboBox.getSelectedIndex());
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    for (Map.Entry<Integer, Project> ee : pl.entrySet()) {
                        if (ptitle.equals(ee.getValue().getTitle())) {
                            selectedProjectNameLabel.setText(ee.getValue().getTitle());
                            selectedProjectOwnerValue.setText(ee.getValue().getOwner().getName());
                            selectedProjectPeopleInvolvedValue.setText(Integer.toString(ee.getValue().getContributors().size()));
                            selectedProjectEndDateValue.setText(ee.getValue().getEndDate().toString());
                            selectedProjectStartDateValue.setText( ee.getValue().getBeginDate().toString());
                            selectedProjectProjectStateValue.setText(ee.getValue().getProjectState().toString());
                            selectedProjectTasksNumberValue.setText( Integer.toString(ee.getValue().getLists().size()));
                        }
                    }
                }
            }
        });*/
            }});
        mainMenuPanel.add(projectListComboBox);
        projectListComboBox.setBounds(20, 20, 220, 22);

        editProfileButton.setText("Edit Profile");
        editProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileButtonActionPerformed(evt);
            }
        });
        mainMenuPanel.add(editProfileButton);
        editProfileButton.setBounds(360, 20, 87, 23);

        addProjectButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaod\\Desktop\\plus.png")); // NOI18N
        addProjectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProjectButtonMouseClicked(evt);
            }
        });
        mainMenuPanel.add(addProjectButton);
        addProjectButton.setBounds(260, 20, 23, 24);

        removeProjectButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaod\\Desktop\\minus.png")); // NOI18N
        removeProjectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeProjectButtonMouseClicked(evt);
            }
        });
        mainMenuPanel.add(removeProjectButton);
        removeProjectButton.setBounds(300, 20, 23, 24);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainMenuPanel.add(jButton1);
        jButton1.setBounds(490, 20, 73, 23);

        getContentPane().add(mainMenuPanel);
        mainMenuPanel.setBounds(10, 6, 1260, 60);

        selectedProjectPanel.setOpaque(false);
        selectedProjectPanel.setLayout(null);

        selectedProjectOwnerValue1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectOwnerValue1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectedProjectPanel.add(selectedProjectOwnerValue1);
        selectedProjectOwnerValue1.setBounds(509, 244, 331, 22);

        selectedProjectStartDateValue1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectStartDateValue1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectedProjectPanel.add(selectedProjectStartDateValue1);
        selectedProjectStartDateValue1.setBounds(509, 364, 331, 22);

        selectedProjectStartDateLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectStartDateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectedProjectStartDateLabel1.setText("Start Date:");
        selectedProjectPanel.add(selectedProjectStartDateLabel1);
        selectedProjectStartDateLabel1.setBounds(189, 364, 310, 22);

        selectedProjectProjectStateLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectProjectStateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectedProjectProjectStateLabel1.setText("Project State:");
        selectedProjectPanel.add(selectedProjectProjectStateLabel1);
        selectedProjectProjectStateLabel1.setBounds(189, 324, 310, 22);

        selectedProjectTasksNumberLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectTasksNumberLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectedProjectTasksNumberLabel1.setText("Tasks Number:");
        selectedProjectPanel.add(selectedProjectTasksNumberLabel1);
        selectedProjectTasksNumberLabel1.setBounds(189, 444, 310, 22);

        selectedProjectEndDateLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectEndDateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectedProjectEndDateLabel1.setText("End Date:");
        selectedProjectPanel.add(selectedProjectEndDateLabel1);
        selectedProjectEndDateLabel1.setBounds(189, 404, 310, 22);

        selectedProjectEndDateValue1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectEndDateValue1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectedProjectPanel.add(selectedProjectEndDateValue1);
        selectedProjectEndDateValue1.setBounds(509, 404, 331, 22);

        selectedProjectPeopleInvolvedLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectPeopleInvolvedLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectedProjectPeopleInvolvedLabel1.setText("People Involved:");
        selectedProjectPanel.add(selectedProjectPeopleInvolvedLabel1);
        selectedProjectPeopleInvolvedLabel1.setBounds(189, 284, 310, 22);

        selectedProjectOwnerLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectOwnerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectedProjectOwnerLabel1.setText("Owner:");
        selectedProjectPanel.add(selectedProjectOwnerLabel1);
        selectedProjectOwnerLabel1.setBounds(189, 244, 310, 22);

        selectedProjectProjectStateValue1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectProjectStateValue1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectedProjectPanel.add(selectedProjectProjectStateValue1);
        selectedProjectProjectStateValue1.setBounds(509, 324, 331, 22);

        selectedProjectNameLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        selectedProjectNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedProjectNameLabel1.setText("Select a Project to View its Details");
        selectedProjectPanel.add(selectedProjectNameLabel1);
        selectedProjectNameLabel1.setBounds(300, 60, 610, 29);

        selectedProjectTasksNumberValue1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectTasksNumberValue1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectedProjectPanel.add(selectedProjectTasksNumberValue1);
        selectedProjectTasksNumberValue1.setBounds(509, 444, 331, 22);

        selectedProjectPeopleInvolvedValue1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectedProjectPeopleInvolvedValue1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectedProjectPanel.add(selectedProjectPeopleInvolvedValue1);
        selectedProjectPeopleInvolvedValue1.setBounds(509, 284, 331, 22);

        selectedProjectBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaod\\Desktop\\BackgroundWavesGreen2.png")); // NOI18N
        selectedProjectPanel.add(selectedProjectBackground);
        selectedProjectBackground.setBounds(0, 0, 1260, 700);

        getContentPane().add(selectedProjectPanel);
        selectedProjectPanel.setBounds(10, 90, 1260, 700);

        dashboardPanel.setBackground(new java.awt.Color(36, 80, 218));
        dashboardPanel.setOpaque(false);
        dashboardPanel.setLayout(null);

        lateProjectsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lateProjectsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lateProjectsLabel.setText("Late Projects");
        dashboardPanel.add(lateProjectsLabel);
        lateProjectsLabel.setBounds(6, 318, 326, 29);

        ongoingProjectsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ongoingProjectsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ongoingProjectsLabel.setText("Ongoing Projects");
        dashboardPanel.add(ongoingProjectsLabel);
        ongoingProjectsLabel.setBounds(6, 202, 326, 29);

        completedProjectsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        completedProjectsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completedProjectsLabel.setText("Completed Projects");
        dashboardPanel.add(completedProjectsLabel);
        completedProjectsLabel.setBounds(6, 71, 326, 29);

        completedProjectsValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        completedProjectsValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completedProjectsValueLabel.setText("completedProjectsValueLabel");
        dashboardPanel.add(completedProjectsValueLabel);
        completedProjectsValueLabel.setBounds(6, 118, 326, 25);

        ongoingProjectsValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ongoingProjectsValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ongoingProjectsValueLabel.setText("ongoingProjectsValueLabel");
        dashboardPanel.add(ongoingProjectsValueLabel);
        ongoingProjectsValueLabel.setBounds(6, 249, 326, 25);

        lateProjectsValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lateProjectsValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lateProjectsValueLabel.setText("lateProjectsValueLabel");
        dashboardPanel.add(lateProjectsValueLabel);
        lateProjectsValueLabel.setBounds(6, 365, 326, 25);

        inNeedOfAttentionLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        inNeedOfAttentionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inNeedOfAttentionLabel.setText("In Need of Attention");
        dashboardPanel.add(inNeedOfAttentionLabel);
        inNeedOfAttentionLabel.setBounds(410, 70, 326, 29);

        inoaProject2ValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inoaProject2ValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inoaProject2ValueLabel.setText("inoaProject2ValueLabel");
        dashboardPanel.add(inoaProject2ValueLabel);
        inoaProject2ValueLabel.setBounds(360, 230, 326, 40);

        inoaProject3ValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inoaProject3ValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inoaProject3ValueLabel.setText("inoaProject3ValueLabel");
        dashboardPanel.add(inoaProject3ValueLabel);
        inoaProject3ValueLabel.setBounds(110, 310, 576, 40);

        inoaProject1ValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inoaProject1ValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inoaProject1ValueLabel.setText("inoaProject1ValueLabel");
        dashboardPanel.add(inoaProject1ValueLabel);
        inoaProject1ValueLabel.setBounds(250, 150, 576, 40);

        biggestProjectLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        biggestProjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biggestProjectLabel.setText("Biggest Project");
        dashboardPanel.add(biggestProjectLabel);
        biggestProjectLabel.setBounds(700, 70, 326, 29);

        bpPeopleInvolvedLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bpPeopleInvolvedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpPeopleInvolvedLabel.setText("People Involved in Project:");
        dashboardPanel.add(bpPeopleInvolvedLabel);
        bpPeopleInvolvedLabel.setBounds(700, 190, 326, 28);

        bpPeopleInvolvedValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bpPeopleInvolvedValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpPeopleInvolvedValueLabel.setText("bpPeopleInvolvedValueLabel");
        dashboardPanel.add(bpPeopleInvolvedValueLabel);
        bpPeopleInvolvedValueLabel.setBounds(700, 230, 326, 22);

        bpCompletedTasksLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bpCompletedTasksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpCompletedTasksLabel.setText("Completed Tasks in Project:");
        dashboardPanel.add(bpCompletedTasksLabel);
        bpCompletedTasksLabel.setBounds(700, 290, 326, 25);

        bpNameValueLabel.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        bpNameValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpNameValueLabel.setText("bpNameValueLabel");
        dashboardPanel.add(bpNameValueLabel);
        bpNameValueLabel.setBounds(700, 120, 326, 22);

        bpCompletedTasksValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bpCompletedTasksValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpCompletedTasksValueLabel.setText("bpCompletedTasksValueLabel");
        dashboardPanel.add(bpCompletedTasksValueLabel);
        bpCompletedTasksValueLabel.setBounds(700, 330, 326, 22);

        dashboardBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaod\\Desktop\\BackgroundWavesBlue2.png")); // NOI18N
        dashboardPanel.add(dashboardBackground);
        dashboardBackground.setBounds(0, 0, 1260, 700);

        getContentPane().add(dashboardPanel);
        dashboardPanel.setBounds(10, 90, 1260, 700);

        homepageBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaod\\Desktop\\cropped-cool-background.png")); // NOI18N
        getContentPane().add(homepageBackground);
        homepageBackground.setBounds(0, 0, 1280, 800);

        setSize(new java.awt.Dimension(1296, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileButtonActionPerformed
        ManageUserAccount mua = new ManageUserAccount(connectedUser);
        mua.setVisible(true);
    }//GEN-LAST:event_editProfileButtonActionPerformed

    private void addProjectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProjectButtonMouseClicked
        NewProject newp = new NewProject(connectedUser);
        newp.setModal(true);
        newp.setVisible(true);
        updateHomepage();
    }//GEN-LAST:event_addProjectButtonMouseClicked

    private void removeProjectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeProjectButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_removeProjectButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (dashboardPanel.isVisible()) {
            this.dashboardPanel.setVisible(false);
            this.selectedProjectPanel.setVisible(true);
        } else {
            this.selectedProjectPanel.setVisible(false);
            this.dashboardPanel.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newProjectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        NewProject newp = new NewProject(connectedUser);
        newp.setModal(true);
        newp.setVisible(true);
        updateHomepage();
    }

    public String inoaProjects1GetText(ArrayList<Task> tasks) {
        try {
            return (tasks.get(0).getTitle());
        } catch (IndexOutOfBoundsException e) {
            e.printStackTrace();
            return ("No projects in need of attention yet.");
        }
    }

    public String inoaProjects2GetText(ArrayList<Task> tasks) {
        try {
            return (tasks.get(1).getTitle());
        } catch (IndexOutOfBoundsException e) {
            e.printStackTrace();
            return ("None.");
        }
    }

    public String inoaProjects3GetText(ArrayList<Task> tasks) {
        try {
            return (tasks.get(2).getTitle());
        } catch (IndexOutOfBoundsException e) {
            e.printStackTrace();
            return ("None.");
        }
    }

    private void updateHomepage() {
        this.dispose();
        HiProject hiProject = new Serialization(String.format("%s\\HiProject.data", System.getProperty("user.dir"))).load();
        try {
            User updatedConnectedUser = hiProject.getUsers().getUser(connectedUser.getEmail());
            new Homepage(updatedConnectedUser).setVisible(true);
        } catch (UserDoesntExistException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage(connectedUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addProjectButton;
    private javax.swing.JLabel biggestProjectLabel;
    private javax.swing.JLabel bpCompletedTasksLabel;
    private javax.swing.JLabel bpCompletedTasksValueLabel;
    private javax.swing.JLabel bpNameValueLabel;
    private javax.swing.JLabel bpPeopleInvolvedLabel;
    private javax.swing.JLabel bpPeopleInvolvedValueLabel;
    private javax.swing.JLabel completedProjectsLabel;
    private javax.swing.JLabel completedProjectsValueLabel;
    private javax.swing.JLabel dashboardBackground;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JButton editProfileButton;
    private javax.swing.JLabel homepageBackground;
    private javax.swing.JLabel inNeedOfAttentionLabel;
    private javax.swing.JLabel inoaProject1ValueLabel;
    private javax.swing.JLabel inoaProject2ValueLabel;
    private javax.swing.JLabel inoaProject3ValueLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lateProjectsLabel;
    private javax.swing.JLabel lateProjectsValueLabel;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel ongoingProjectsLabel;
    private javax.swing.JLabel ongoingProjectsValueLabel;
    private javax.swing.JComboBox<String> projectListComboBox;
    private javax.swing.JLabel removeProjectButton;
    private javax.swing.JLabel selectedProjectBackground;
    private javax.swing.JLabel selectedProjectEndDateLabel1;
    private javax.swing.JLabel selectedProjectEndDateValue1;
    private javax.swing.JLabel selectedProjectNameLabel1;
    private javax.swing.JLabel selectedProjectOwnerLabel1;
    private javax.swing.JLabel selectedProjectOwnerValue1;
    private javax.swing.JPanel selectedProjectPanel;
    private javax.swing.JLabel selectedProjectPeopleInvolvedLabel1;
    private javax.swing.JLabel selectedProjectPeopleInvolvedValue1;
    private javax.swing.JLabel selectedProjectProjectStateLabel1;
    private javax.swing.JLabel selectedProjectProjectStateValue1;
    private javax.swing.JLabel selectedProjectStartDateLabel1;
    private javax.swing.JLabel selectedProjectStartDateValue1;
    private javax.swing.JLabel selectedProjectTasksNumberLabel1;
    private javax.swing.JLabel selectedProjectTasksNumberValue1;
    // End of variables declaration//GEN-END:variables
}
