/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.src;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.time.LocalDate;
import java.util.*;

import Backend.*;
import Exceptions.UserDoesntExistException;

import java.lang.reflect.Array;

import javax.swing.*;

/**
 * @author joaod
 */
public class Homepage extends javax.swing.JFrame {
    private static User connectedUser;
    private Map<Integer, Project> pl;
    private static ArrayList<String> titles = new ArrayList<>();
    private ArrayList<String> projectsmta(ArrayList<String> ptitles) {
        ptitles.clear();
        ptitles.add("< Please Select a Project >");
        for (Map.Entry<Integer, Project> e : pl.entrySet()) {
            ptitles.add(e.getValue().getTitle());
        }
        return ptitles;
    }

    /**
     * Creates new form Homepage
     */
    public Homepage(User connectedUser) {
        Homepage.connectedUser = connectedUser;
        pl = connectedUser.getProjects().getProjects();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        projectListComboBox = new javax.swing.JComboBox<>();
        editProfileButton = new javax.swing.JButton();
        addProjectButton = new javax.swing.JLabel();
        removeProjectButton = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        selectedProjectPanel = new javax.swing.JPanel();
        sppSelectedProjectDescriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sppSelectedProjectDescriptionValue = new javax.swing.JTextArea();
        sppSelectedProjectEditProjectButtonLabel = new javax.swing.JLabel();
        sppSelectedProjectEditProjectButton = new javax.swing.JLabel();
        sppSelectedProjectStateValue = new javax.swing.JLabel();
        sppSelectedProjectStartDateValue = new javax.swing.JLabel();
        sppSelectedProjectStartDateLabel = new javax.swing.JLabel();
        sppSelectedProjectEndDateValue = new javax.swing.JLabel();
        sppSelectedProjectEndDateLabel = new javax.swing.JLabel();
        sppSelectedProjectStateLabel = new javax.swing.JLabel();
        sppSelectedProjectOwner = new javax.swing.JLabel();
        sppSelectedProjectName = new javax.swing.JLabel();
        selectedProjectBackground = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        completedProjectsLabel = new javax.swing.JLabel();
        completedProjectsValueLabel = new javax.swing.JLabel();
        ongoingProjectsLabel = new javax.swing.JLabel();
        ongoingProjectsValueLabel = new javax.swing.JLabel();
        lateProjectsLabel = new javax.swing.JLabel();
        lateProjectsValueLabel = new javax.swing.JLabel();
        inNeedOfAttentionLabel = new javax.swing.JLabel();
        inoaProject2ValueLabel = new javax.swing.JLabel();
        inoaProject3ValueLabel = new javax.swing.JLabel();
        inoaProject1ValueLabel = new javax.swing.JLabel();
        biggestProjectLabel = new javax.swing.JLabel();
        bpPeopleInvolvedLabel = new javax.swing.JLabel();
        bpPeopleInvolvedValueLabel = new javax.swing.JLabel();
        bpCompletedTasksLabel = new javax.swing.JLabel();
        bpNameValueLabel = new javax.swing.JLabel();
        bpCompletedTasksValueLabel = new javax.swing.JLabel();
        dashboardBackground = new javax.swing.JLabel();
        homepageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Homepage");
        getContentPane().setLayout(null);

        mainMenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Welcome to HiProject, " + connectedUser.getName()));
        mainMenuPanel.setOpaque(false);
        mainMenuPanel.setLayout(null);

        projectListComboBox.setModel(new javax.swing.DefaultComboBoxModel(projectsmta(titles).toArray()));
        projectListComboBox.addItemListener (new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                String ptitle = projectListComboBox.getItemAt(projectListComboBox.getSelectedIndex());
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    for (Map.Entry<Integer, Project> ee : pl.entrySet()) {
                        if (ptitle.equals(ee.getValue().getTitle())) {
                            sppSelectedProjectName.setText(ee.getValue().getTitle());
                            sppSelectedProjectOwner.setText(ee.getValue().getOwner().getName());
                            //selectedProjectPeopleInvolvedValue.setText(Integer.toString(ee.getValue().getContributors().size()));
                            sppSelectedProjectEndDateValue.setText(ee.getValue().getEndDate().toString());
                            sppSelectedProjectStartDateValue.setText( ee.getValue().getBeginDate().toString());
                            sppSelectedProjectStateValue.setText(ee.getValue().getProjectState().toString());
                            //selectedProjectTasksNumberValue.setText( Integer.toString(ee.getValue().getLists().size()));
                        }
                    }
                }
            }
        });
        mainMenuPanel.add(projectListComboBox);
        projectListComboBox.setBounds(20, 30, 220, 30);

        editProfileButton.setText("Edit Profile");
        editProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileButtonActionPerformed(evt);
            }
        });
        mainMenuPanel.add(editProfileButton);
        editProfileButton.setBounds(360, 30, 87, 23);

        addProjectButton.setIcon(new javax.swing.ImageIcon(String.format("%s\\Images\\Plus.png", System.getProperty("user.dir"))));
        addProjectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProjectButtonMouseClicked(evt);
            }
        });
        mainMenuPanel.add(addProjectButton);
        addProjectButton.setBounds(260, 30, 30, 30);

        removeProjectButton.setIcon(new javax.swing.ImageIcon(String.format("%s\\Images\\Minus.png", System.getProperty("user.dir"))));
        removeProjectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeProjectButtonMouseClicked(evt);
            }
        });
        mainMenuPanel.add(removeProjectButton);
        removeProjectButton.setBounds(300, 30, 30, 30);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainMenuPanel.add(jButton1);
        jButton1.setBounds(490, 30, 73, 23);

        getContentPane().add(mainMenuPanel);
        mainMenuPanel.setBounds(10, 6, 1320, 80);

        selectedProjectPanel.setOpaque(false);
        selectedProjectPanel.setLayout(null);

        sppSelectedProjectDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sppSelectedProjectDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sppSelectedProjectDescriptionLabel.setText("Project Description");
        selectedProjectPanel.add(sppSelectedProjectDescriptionLabel);
        sppSelectedProjectDescriptionLabel.setBounds(510, 160, 210, 30);

        sppSelectedProjectDescriptionValue.setColumns(20);
        sppSelectedProjectDescriptionValue.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sppSelectedProjectDescriptionValue.setRows(5);
        sppSelectedProjectDescriptionValue.setText("codigo get description\n");
        sppSelectedProjectDescriptionValue.setBorder(null);
        sppSelectedProjectDescriptionValue.setFocusable(false);
        sppSelectedProjectDescriptionValue.setOpaque(false);
        jScrollPane1.setViewportView(sppSelectedProjectDescriptionValue);

        selectedProjectPanel.add(jScrollPane1);
        jScrollPane1.setBounds(450, 200, 330, 140);

        sppSelectedProjectEditProjectButtonLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sppSelectedProjectEditProjectButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sppSelectedProjectEditProjectButtonLabel.setText("Edit Project");
        selectedProjectPanel.add(sppSelectedProjectEditProjectButtonLabel);
        sppSelectedProjectEditProjectButtonLabel.setBounds(1210, 100, 80, 30);

        sppSelectedProjectEditProjectButton.setIcon(new javax.swing.ImageIcon(String.format("%s\\Images\\EditButton64px.png", System.getProperty("user.dir"))));
        sppSelectedProjectEditProjectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sppSelectedProjectEditProjectButtonMouseClicked(evt);
            }
        });
        selectedProjectPanel.add(sppSelectedProjectEditProjectButton);
        sppSelectedProjectEditProjectButton.setBounds(1220, 30, 70, 70);

        sppSelectedProjectStateValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sppSelectedProjectStateValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sppSelectedProjectStateValue.setText("code ---");
        selectedProjectPanel.add(sppSelectedProjectStateValue);
        sppSelectedProjectStateValue.setBounds(280, 160, 200, 40);

        sppSelectedProjectStartDateValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sppSelectedProjectStartDateValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sppSelectedProjectStartDateValue.setText("codigo");
        selectedProjectPanel.add(sppSelectedProjectStartDateValue);
        sppSelectedProjectStartDateValue.setBounds(280, 210, 200, 40);

        sppSelectedProjectStartDateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sppSelectedProjectStartDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sppSelectedProjectStartDateLabel.setText("Project started on:");
        selectedProjectPanel.add(sppSelectedProjectStartDateLabel);
        sppSelectedProjectStartDateLabel.setBounds(0, 210, 250, 40);

        sppSelectedProjectEndDateValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sppSelectedProjectEndDateValue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sppSelectedProjectEndDateValue.setText("codigo");
        selectedProjectPanel.add(sppSelectedProjectEndDateValue);
        sppSelectedProjectEndDateValue.setBounds(280, 260, 200, 40);

        sppSelectedProjectEndDateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sppSelectedProjectEndDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sppSelectedProjectEndDateLabel.setText("Project should end by:");
        selectedProjectPanel.add(sppSelectedProjectEndDateLabel);
        sppSelectedProjectEndDateLabel.setBounds(0, 260, 250, 40);

        sppSelectedProjectStateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sppSelectedProjectStateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sppSelectedProjectStateLabel.setText("Project is currently:");
        selectedProjectPanel.add(sppSelectedProjectStateLabel);
        sppSelectedProjectStateLabel.setBounds(0, 160, 250, 40);

        sppSelectedProjectOwner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sppSelectedProjectOwner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sppSelectedProjectOwner.setText("codigo: settxt(\"owned by \" + owner)");
        selectedProjectPanel.add(sppSelectedProjectOwner);
        sppSelectedProjectOwner.setBounds(460, 90, 310, 40);

        sppSelectedProjectName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sppSelectedProjectName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sppSelectedProjectName.setText("codigo: txt getprojename");
        selectedProjectPanel.add(sppSelectedProjectName);
        sppSelectedProjectName.setBounds(310, 19, 610, 60);

        selectedProjectBackground.setIcon(new javax.swing.ImageIcon(String.format("%s\\Images\\ProjectBackground.png", System.getProperty("user.dir"))));
        selectedProjectPanel.add(selectedProjectBackground);
        selectedProjectBackground.setBounds(0, 0, 1320, 800);

        getContentPane().add(selectedProjectPanel);
        selectedProjectPanel.setBounds(10, 90, 1320, 800);

        dashboardPanel.setBackground(new java.awt.Color(36, 80, 218));
        dashboardPanel.setOpaque(false);
        dashboardPanel.setLayout(null);

        completedProjectsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        completedProjectsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completedProjectsLabel.setText("Completed Projects");
        dashboardPanel.add(completedProjectsLabel);
        completedProjectsLabel.setBounds(90, 630, 326, 29);

        completedProjectsValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        completedProjectsValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completedProjectsValueLabel.setText("completedProjectsValueLabel");
        dashboardPanel.add(completedProjectsValueLabel);
        completedProjectsValueLabel.setBounds(90, 690, 326, 25);

        ongoingProjectsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ongoingProjectsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ongoingProjectsLabel.setText("Ongoing Projects");
        dashboardPanel.add(ongoingProjectsLabel);
        ongoingProjectsLabel.setBounds(500, 630, 326, 29);

        ongoingProjectsValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ongoingProjectsValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ongoingProjectsValueLabel.setText("ongoingProjectsValueLabel");
        dashboardPanel.add(ongoingProjectsValueLabel);
        ongoingProjectsValueLabel.setBounds(500, 680, 326, 25);

        lateProjectsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lateProjectsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lateProjectsLabel.setText("Late Projects");
        dashboardPanel.add(lateProjectsLabel);
        lateProjectsLabel.setBounds(890, 630, 326, 29);

        lateProjectsValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lateProjectsValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lateProjectsValueLabel.setText("lateProjectsValueLabel");
        dashboardPanel.add(lateProjectsValueLabel);
        lateProjectsValueLabel.setBounds(890, 680, 326, 25);

        inNeedOfAttentionLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        inNeedOfAttentionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inNeedOfAttentionLabel.setText("In Need of Attention");
        dashboardPanel.add(inNeedOfAttentionLabel);
        inNeedOfAttentionLabel.setBounds(230, 120, 326, 29);

        inoaProject2ValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inoaProject2ValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inoaProject2ValueLabel.setText("inoaProject2ValueLabel");
        dashboardPanel.add(inoaProject2ValueLabel);
        inoaProject2ValueLabel.setBounds(240, 330, 326, 40);

        inoaProject3ValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inoaProject3ValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inoaProject3ValueLabel.setText("inoaProject3ValueLabel");
        dashboardPanel.add(inoaProject3ValueLabel);
        inoaProject3ValueLabel.setBounds(200, 410, 420, 40);

        inoaProject1ValueLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inoaProject1ValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inoaProject1ValueLabel.setText("inoaProject1ValueLabel");
        dashboardPanel.add(inoaProject1ValueLabel);
        inoaProject1ValueLabel.setBounds(230, 250, 360, 40);

        biggestProjectLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        biggestProjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biggestProjectLabel.setText("Biggest Project");
        dashboardPanel.add(biggestProjectLabel);
        biggestProjectLabel.setBounds(790, 90, 326, 29);

        bpPeopleInvolvedLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bpPeopleInvolvedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpPeopleInvolvedLabel.setText("People Involved in Project:");
        dashboardPanel.add(bpPeopleInvolvedLabel);
        bpPeopleInvolvedLabel.setBounds(800, 260, 326, 28);

        bpPeopleInvolvedValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bpPeopleInvolvedValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpPeopleInvolvedValueLabel.setText("bpPeopleInvolvedValueLabel");
        dashboardPanel.add(bpPeopleInvolvedValueLabel);
        bpPeopleInvolvedValueLabel.setBounds(800, 320, 326, 22);

        bpCompletedTasksLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bpCompletedTasksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpCompletedTasksLabel.setText("Completed Tasks in Project:");
        dashboardPanel.add(bpCompletedTasksLabel);
        bpCompletedTasksLabel.setBounds(800, 390, 326, 25);

        bpNameValueLabel.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        bpNameValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpNameValueLabel.setText("bpNameValueLabel");
        dashboardPanel.add(bpNameValueLabel);
        bpNameValueLabel.setBounds(790, 170, 326, 22);

        bpCompletedTasksValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bpCompletedTasksValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpCompletedTasksValueLabel.setText("bpCompletedTasksValueLabel");
        dashboardPanel.add(bpCompletedTasksValueLabel);
        bpCompletedTasksValueLabel.setBounds(800, 460, 326, 22);

        dashboardBackground.setIcon(new javax.swing.ImageIcon(String.format("%s\\Images\\DashboardBackground.png", System.getProperty("user.dir"))));
        dashboardPanel.add(dashboardBackground);
        dashboardBackground.setBounds(0, 0, 1320, 800);

        getContentPane().add(dashboardPanel);
        dashboardPanel.setBounds(10, 90, 1320, 800);

        homepageBackground.setIcon(new javax.swing.ImageIcon(String.format("%s\\Images\\DefaultBackground.png", System.getProperty("user.dir"))));
        getContentPane().add(homepageBackground);
        homepageBackground.setBounds(0, 0, 1350, 910);

        setSize(new java.awt.Dimension(1356, 938));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileButtonActionPerformed
        ManageUserAccount mua = new ManageUserAccount(connectedUser);
        mua.setVisible(true);
    }//GEN-LAST:event_editProfileButtonActionPerformed

    private void addProjectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProjectButtonMouseClicked
        NewProject newp = new NewProject(connectedUser);
        newp.setModal(true);
        newp.setVisible(true);
        updateHomepage();
    }//GEN-LAST:event_addProjectButtonMouseClicked

    private void removeProjectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeProjectButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_removeProjectButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (dashboardPanel.isVisible()) {
            this.dashboardPanel.setVisible(false);
            this.selectedProjectPanel.setVisible(true);
        } else {
            this.selectedProjectPanel.setVisible(false);
            this.dashboardPanel.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sppSelectedProjectEditProjectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sppSelectedProjectEditProjectButtonMouseClicked
        EditProject newep = new EditProject(this, rootPaneCheckingEnabled);
        newep.setVisible(true);
    }//GEN-LAST:event_sppSelectedProjectEditProjectButtonMouseClicked

    private void newProjectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        NewProject newp = new NewProject(connectedUser);
        newp.setModal(true);
        newp.setVisible(true);
        updateHomepage();
    }

    public String inoaProjects1GetText(ArrayList<Task> tasks) {
        try {
            return (tasks.get(0).getTitle());
        } catch (IndexOutOfBoundsException e) {
            e.printStackTrace();
            return ("No projects in need of attention yet.");
        }
    }

    public String inoaProjects2GetText(ArrayList<Task> tasks) {
        try {
            return (tasks.get(1).getTitle());
        } catch (IndexOutOfBoundsException e) {
            e.printStackTrace();
            return ("None.");
        }
    }

    public String inoaProjects3GetText(ArrayList<Task> tasks) {
        try {
            return (tasks.get(2).getTitle());
        } catch (IndexOutOfBoundsException e) {
            e.printStackTrace();
            return ("None.");
        }
    }

    private void updateHomepage() {
        this.dispose();
        HiProject hiProject = new Serialization(String.format("%s\\HiProject.data", System.getProperty("user.dir"))).load();
        try {
            User updatedConnectedUser = hiProject.getUsers().getUser(connectedUser.getEmail());
            new Homepage(updatedConnectedUser).setVisible(true);
        } catch (UserDoesntExistException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage(connectedUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addProjectButton;
    private javax.swing.JLabel biggestProjectLabel;
    private javax.swing.JLabel bpCompletedTasksLabel;
    private javax.swing.JLabel bpCompletedTasksValueLabel;
    private javax.swing.JLabel bpNameValueLabel;
    private javax.swing.JLabel bpPeopleInvolvedLabel;
    private javax.swing.JLabel bpPeopleInvolvedValueLabel;
    private javax.swing.JLabel completedProjectsLabel;
    private javax.swing.JLabel completedProjectsValueLabel;
    private javax.swing.JLabel dashboardBackground;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JButton editProfileButton;
    private javax.swing.JLabel homepageBackground;
    private javax.swing.JLabel inNeedOfAttentionLabel;
    private javax.swing.JLabel inoaProject1ValueLabel;
    private javax.swing.JLabel inoaProject2ValueLabel;
    private javax.swing.JLabel inoaProject3ValueLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lateProjectsLabel;
    private javax.swing.JLabel lateProjectsValueLabel;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel ongoingProjectsLabel;
    private javax.swing.JLabel ongoingProjectsValueLabel;
    private javax.swing.JComboBox<String> projectListComboBox;
    private javax.swing.JLabel removeProjectButton;
    private javax.swing.JLabel selectedProjectBackground;
    private javax.swing.JPanel selectedProjectPanel;
    private javax.swing.JLabel sppSelectedProjectDescriptionLabel;
    private javax.swing.JTextArea sppSelectedProjectDescriptionValue;
    private javax.swing.JLabel sppSelectedProjectEditProjectButton;
    private javax.swing.JLabel sppSelectedProjectEditProjectButtonLabel;
    private javax.swing.JLabel sppSelectedProjectEndDateLabel;
    private javax.swing.JLabel sppSelectedProjectEndDateValue;
    private javax.swing.JLabel sppSelectedProjectName;
    private javax.swing.JLabel sppSelectedProjectOwner;
    private javax.swing.JLabel sppSelectedProjectStartDateLabel;
    private javax.swing.JLabel sppSelectedProjectStartDateValue;
    private javax.swing.JLabel sppSelectedProjectStateLabel;
    private javax.swing.JLabel sppSelectedProjectStateValue;
    // End of variables declaration//GEN-END:variables
}
