/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.src;
import Backend.*;

import javax.swing.*;
import java.time.LocalDate;

/**
 *
 * @author joaod
 */
public class ManageUserAccount extends javax.swing.JFrame {
    private static User connectedUser;
    private Serialization serialization = new Serialization(String.format("%s\\HiProject.data", System.getProperty("user.dir")));

    /**
     * Creates new form ManageUserAccount
     */
    public ManageUserAccount(User connectedUser) {
        ManageUserAccount.connectedUser = connectedUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        userEmailLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        exitDontSaveButton = new javax.swing.JButton();
        saveChangesButton = new javax.swing.JButton();
        userEmailField = new javax.swing.JTextField();
        newPasswordField = new javax.swing.JPasswordField();
        confirmPasswordLabel = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        manageYourUserProfileLabel = new javax.swing.JLabel();
        passwordChangeInfo1 = new javax.swing.JLabel();
        passwordChangeLabel = new javax.swing.JLabel();
        currentPasswordLabel = new javax.swing.JLabel();
        currentPasswordField = new javax.swing.JPasswordField();
        passwordChangeInfo2 = new javax.swing.JLabel();
        defaultBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Account Manager");

        jPanel1.setLayout(null);

        userNameLabel.setText("Name");
        userNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(userNameLabel);
        userNameLabel.setBounds(42, 95, 35, 17);

        userNameField.setText(connectedUser.getName());
        jPanel1.add(userNameField);
        userNameField.setBounds(95, 90, 282, 30);

        userEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userEmailLabel.setText("Email");
        jPanel1.add(userEmailLabel);
        userEmailLabel.setBounds(50, 150, 33, 17);

        newPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newPasswordLabel.setText("New Password");
        jPanel1.add(newPasswordLabel);
        newPasswordLabel.setBounds(36, 360, 88, 17);

        exitDontSaveButton.setText("Exit & Don't Save");
        exitDontSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitDontSaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitDontSaveButton);
        exitDontSaveButton.setBounds(219, 460, 140, 23);

        saveChangesButton.setText("Save Changes");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveChangesButton);
        saveChangesButton.setBounds(63, 460, 120, 23);

        userEmailField.setText(connectedUser.getEmail());
        userEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(userEmailField);
        userEmailField.setBounds(95, 145, 282, 30);
        jPanel1.add(newPasswordField);
        newPasswordField.setBounds(167, 360, 210, 20);

        confirmPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmPasswordLabel.setText("Confirm Password");
        jPanel1.add(confirmPasswordLabel);
        confirmPasswordLabel.setBounds(36, 400, 113, 17);
        jPanel1.add(confirmPasswordField);
        confirmPasswordField.setBounds(167, 400, 210, 20);

        manageYourUserProfileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageYourUserProfileLabel.setText("Manage your User Profile");
        manageYourUserProfileLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(manageYourUserProfileLabel);
        manageYourUserProfileLabel.setBounds(1, 31, 416, 29);

        passwordChangeInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordChangeInfo1.setText("If you wish to change your user password, please fill in the following fields.");
        jPanel1.add(passwordChangeInfo1);
        passwordChangeInfo1.setBounds(1, 262, 416, 14);

        passwordChangeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordChangeLabel.setText("Password Change");
        passwordChangeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(passwordChangeLabel);
        passwordChangeLabel.setBounds(1, 222, 416, 22);

        currentPasswordLabel.setText("Current Password");
        currentPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(currentPasswordLabel);
        currentPasswordLabel.setBounds(36, 320, 108, 17);

        currentPasswordField.setText("jPasswordField1");
        jPanel1.add(currentPasswordField);
        currentPasswordField.setBounds(167, 320, 210, 20);

        passwordChangeInfo2.setText("Otherwise, please leave them empty.");
        jPanel1.add(passwordChangeInfo2);
        passwordChangeInfo2.setBounds(24, 281, 181, 14);

        defaultBackground.setIcon(new javax.swing.ImageIcon(String.format("%s\\DefaultBackground.png", System.getProperty("user.dir"))));
        jPanel1.add(defaultBackground);
        defaultBackground.setBounds(0, 0, 420, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(434, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        HiProject hiProject = serialization.load();
        hiProject.editUserProfileAndSerialize(connectedUser, userNameField.getText(), userEmailField.getText(), new String(confirmPasswordField.getPassword()));
        dispose();
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void exitDontSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitDontSaveButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitDontSaveButtonActionPerformed

    private void userEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUserAccount(connectedUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JPasswordField currentPasswordField;
    private javax.swing.JLabel currentPasswordLabel;
    private javax.swing.JLabel defaultBackground;
    private javax.swing.JButton exitDontSaveButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manageYourUserProfileLabel;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel passwordChangeInfo1;
    private javax.swing.JLabel passwordChangeInfo2;
    private javax.swing.JLabel passwordChangeLabel;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JTextField userEmailField;
    private javax.swing.JLabel userEmailLabel;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
