/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.src;

import Backend.*;
import Exceptions.UserDoesntExistException;

import javax.swing.*;
import java.time.LocalDate;

/**
 * @author joaod
 */
public class NewProject extends javax.swing.JFrame {
    private static User connectedUser;
    private HiProject hiProject;
    private Serialization serialization = new Serialization(String.format("%s\\HiProject.data", System.getProperty("user.dir")));

    /**
     * Creates new form NewProject
     */
    public NewProject(User connectedUser) {
        NewProject.connectedUser = connectedUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.\
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newProjectTitleLabel = new javax.swing.JLabel();
        newProjectTitleValueField = new javax.swing.JTextField();
        newProjectDescriptionLabel = new javax.swing.JLabel();
        newProjectEndDateLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        createProjectButton = new javax.swing.JButton();
        newProjectEndDateValueField = new com.github.lgooddatepicker.components.DatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        newProjectDescriptionValueField = new javax.swing.JTextArea();
        newProjectStartDateLabel = new javax.swing.JLabel();
        newProjectStartDateValueField = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Project");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        newProjectTitleLabel.setText("Title");
        newProjectTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        newProjectTitleValueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectTitleValueFieldActionPerformed(evt);
            }
        });

        newProjectDescriptionLabel.setText("Description");
        newProjectDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        newProjectEndDateLabel.setText("End Date");
        newProjectEndDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        createProjectButton.setText("Create");
        createProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectButtonActionPerformed(evt);
            }
        });

        newProjectEndDateValueField.setDate(LocalDate.now().plusDays(1));

        newProjectDescriptionValueField.setColumns(20);
        newProjectDescriptionValueField.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        newProjectDescriptionValueField.setLineWrap(true);
        newProjectDescriptionValueField.setRows(5);
        jScrollPane1.setViewportView(newProjectDescriptionValueField);

        newProjectStartDateLabel.setText("Start Date");
        newProjectStartDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        newProjectStartDateValueField.setDate(LocalDate.now());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(createProjectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newProjectStartDateLabel)
                    .addComponent(newProjectEndDateLabel)
                    .addComponent(newProjectTitleLabel)
                    .addComponent(newProjectDescriptionLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(newProjectTitleValueField)
                    .addComponent(newProjectEndDateValueField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProjectStartDateValueField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProjectTitleLabel)
                    .addComponent(newProjectTitleValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newProjectDescriptionLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProjectStartDateLabel)
                    .addComponent(newProjectStartDateValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProjectEndDateLabel)
                    .addComponent(newProjectEndDateValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProjectButton)
                    .addComponent(exitButton))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectButtonActionPerformed
        hiProject = serialization.load();
        if (newProjectTitleValueField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please insert a project title.");
                newProjectTitleValueField.requestFocus();
            } else if (newProjectDescriptionValueField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please insert a project description.");
                newProjectTitleValueField.requestFocus();
            } else if (newProjectStartDateValueField.getDate().isBefore(LocalDate.now())){
                JOptionPane.showMessageDialog(null, "Please insert a valid project start date.\nThe project cannot start before today.");
                newProjectTitleValueField.requestFocus();
            } else if (newProjectEndDateValueField.getDate().isBefore(newProjectStartDateValueField.getDate().plusDays(1))) {
                JOptionPane.showMessageDialog(null, "Please insert a valid project end date.\nThe project cannot end before or on the same day it starts.");
                newProjectTitleValueField.requestFocus();
            } else {
                hiProject.addProjectAndSerialize(connectedUser, new Project(newProjectTitleValueField.getText(), newProjectDescriptionValueField.getText(),
                        newProjectStartDateValueField.getDate(), newProjectEndDateValueField.getDate(), new Manager(connectedUser)));
                dispose();
            }
    }//GEN-LAST:event_createProjectButtonActionPerformed

    private void newProjectEndDateValueLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectEndDateValueLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProjectEndDateValueLabelActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void newProjectTitleValueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectTitleValueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProjectTitleValueFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProject(connectedUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createProjectButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newProjectDescriptionLabel;
    private javax.swing.JTextArea newProjectDescriptionValueField;
    private javax.swing.JLabel newProjectEndDateLabel;
    private com.github.lgooddatepicker.components.DatePicker newProjectEndDateValueField;
    private javax.swing.JLabel newProjectStartDateLabel;
    private com.github.lgooddatepicker.components.DatePicker newProjectStartDateValueField;
    private javax.swing.JLabel newProjectTitleLabel;
    private javax.swing.JTextField newProjectTitleValueField;
    // End of variables declaration//GEN-END:variables
}
