/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.src;

import Backend.*;

import javax.swing.*;
import java.time.LocalDate;

/**
 * @author joaod
 */
public class NewProject extends javax.swing.JDialog {
    private static User connectedUser;
    private HiProject hiProject;
    private Serialization serialization = new Serialization(String.format("%s\\HiProject.data", System.getProperty("user.dir")));

    /**
     * Creates new form NewProject
     */
    public NewProject(User connectedUser) {
        setModalityType(ModalityType.APPLICATION_MODAL);
        NewProject.connectedUser = connectedUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.\
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newProjectTitleLabel = new javax.swing.JLabel();
        newProjectTitleValueField = new javax.swing.JTextField();
        newProjectDescriptionLabel = new javax.swing.JLabel();
        newProjectEndDateLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        createProjectButton = new javax.swing.JButton();
        newProjectEndDateValueField = new com.github.lgooddatepicker.components.DatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        newProjectDescriptionValueField = new javax.swing.JTextArea();
        newProjectStartDateLabel = new javax.swing.JLabel();
        newProjectStartDateValueField = new com.github.lgooddatepicker.components.DatePicker();
        createNewProjectLabel = new javax.swing.JLabel();
        defaultBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Project");
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(null);

        newProjectTitleLabel.setText("Title");
        newProjectTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(newProjectTitleLabel);
        newProjectTitleLabel.setBounds(68, 91, 26, 17);

        newProjectTitleValueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectTitleValueFieldActionPerformed(evt);
            }
        });
        jPanel1.add(newProjectTitleValueField);
        newProjectTitleValueField.setBounds(112, 91, 270, 30);

        newProjectDescriptionLabel.setText("Description");
        newProjectDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(newProjectDescriptionLabel);
        newProjectDescriptionLabel.setBounds(25, 129, 69, 17);

        newProjectEndDateLabel.setText("End Date");
        newProjectEndDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(newProjectEndDateLabel);
        newProjectEndDateLabel.setBounds(37, 284, 57, 17);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton);
        exitButton.setBounds(269, 353, 51, 23);

        createProjectButton.setText("Create");
        createProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createProjectButton);
        createProjectButton.setBounds(95, 353, 65, 23);

        newProjectEndDateValueField.setDate(LocalDate.now().plusDays(1));
        jPanel1.add(newProjectEndDateValueField);
        newProjectEndDateValueField.setBounds(112, 285, 270, 30);

        newProjectDescriptionValueField.setColumns(20);
        newProjectDescriptionValueField.setLineWrap(true);
        newProjectDescriptionValueField.setRows(5);
        newProjectDescriptionValueField.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(newProjectDescriptionValueField);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(112, 129, 270, 98);

        newProjectStartDateLabel.setText("Start Date");
        newProjectStartDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(newProjectStartDateLabel);
        newProjectStartDateLabel.setBounds(31, 245, 63, 17);

        newProjectStartDateValueField.setDate(LocalDate.now());
        jPanel1.add(newProjectStartDateValueField);
        newProjectStartDateValueField.setBounds(112, 246, 270, 30);

        createNewProjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createNewProjectLabel.setText("Create a New Project");
        createNewProjectLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(createNewProjectLabel);
        createNewProjectLabel.setBounds(1, 20, 413, 50);

        defaultBackground.setIcon(new javax.swing.ImageIcon(String.format("%s\\DefaultBackground.png", System.getProperty("user.dir"))));
        jPanel1.add(defaultBackground);
        defaultBackground.setBounds(0, 0, 420, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(415, 410));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newProjectEndDateValueLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectEndDateValueLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProjectEndDateValueLabelActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void newProjectTitleValueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectTitleValueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProjectTitleValueFieldActionPerformed

    private void createProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectButtonActionPerformed
        hiProject = serialization.load();
        if (newProjectTitleValueField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please insert a project title.");
            newProjectTitleValueField.requestFocus();
        } else if (newProjectDescriptionValueField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please insert a project description.");
            newProjectTitleValueField.requestFocus();
        } else if (newProjectStartDateValueField.getDate().isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(null, "Please insert a valid project start date.\nThe project cannot start before today.");
            newProjectTitleValueField.requestFocus();
        } else if (newProjectEndDateValueField.getDate().isBefore(newProjectStartDateValueField.getDate().plusDays(1))) {
            JOptionPane.showMessageDialog(null, "Please insert a valid project end date.\nThe project cannot end before or on the same day it starts.");
            newProjectTitleValueField.requestFocus();
        } else {
            hiProject.addProjectAndSerialize(connectedUser, new Project(connectedUser.getnextProjectId(), newProjectTitleValueField.getText(), newProjectDescriptionValueField.getText(),
                    newProjectStartDateValueField.getDate(), newProjectEndDateValueField.getDate(), new Manager(connectedUser)));
            dispose();
        }
    }//GEN-LAST:event_createProjectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProject(connectedUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createNewProjectLabel;
    private javax.swing.JButton createProjectButton;
    private javax.swing.JLabel defaultBackground;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newProjectDescriptionLabel;
    private javax.swing.JTextArea newProjectDescriptionValueField;
    private javax.swing.JLabel newProjectEndDateLabel;
    private com.github.lgooddatepicker.components.DatePicker newProjectEndDateValueField;
    private javax.swing.JLabel newProjectStartDateLabel;
    private com.github.lgooddatepicker.components.DatePicker newProjectStartDateValueField;
    private javax.swing.JLabel newProjectTitleLabel;
    private javax.swing.JTextField newProjectTitleValueField;
    // End of variables declaration//GEN-END:variables
}
